name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clippy_fmt:
    name: Rustfmt & Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Enable Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run Clippy lints
        run: cargo clippy --all-targets --all-features -- -D warnings